name: Lua Linting

on:
  push:
    branches:
      - Hearth-Edition-Main
  pull_request:
    branches:
      - Hearth-Edition-Main
  workflow_dispatch:

jobs:
  lint:
    name: Run Luacheck Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua-check

      - name: Run Luacheck Linter
        run: luacheck --config .luacheckrc scripts
